<?php
$z[0]=Array("field","",73,101);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",119,148);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\n                    <li class=\"list-unstyled m-3\">\n                        <div>\n                            <a href=\"[field:arcurl/]\" title=\"[field:title/]​\" target=\"_blank\">\n                                <img src=\"[field:litpic/]\"alt=\"[field:title/]\">                              \n                            </a>\n                        </div>\n                        <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]​\" target=\"_blank\">\n                            <strong>[field:title/]</strong>\n                        </a>\n                        </h3>\n                        <p> [field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]\n                                查看： [field:click/]\n                            </p>\n                    </li>\n                    ",243,1102);
$z[2][4]=array();
$z[2][4]['orderby']="pubdate";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="42";

?>