<div class="row">
                                <div class="col-xl-6 col-lg-4 col-md-5">
                                    <div class="postbox mb-30">
                                        <div class="postbox__thumb">
                                            <a href="[field:arcurl/]">
                                                <img src="[field:litpic/]" alt="[field:title/]">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-8 col-md-7">
                                    <div class="postbox__text mb-30">
                                        <div class="meta-top">
                                            <span class="post-cat mb-10 mr-10">
                                                <a href="[field:typeurl/]" tabindex="0">[field:typename/]</a>
                                            </span>
                                            <span>
                                                <i class="fas fa-calendar-alt"></i> [field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                        </div>
                                        <h4 class="title-16 pr-0">
                                            <a href="[field:arcurl/]">[field:title/]</a>
                                        </h4>
                                        <div class="postbox__text-meta pb-10">
                                            <ul>
                                                <li>
                                                    <i class="fas fa-calendar-alt"></i>
                                                    <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                                </li>
                                                <li>
                                                    <i class="far fa-comment"></i>
                                                    <span>[field:click/]</span>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="desc-text mb-20">
                                            <p>[field:info/]</p>
                                        </div>
                                        <a href="[field:arcurl/]" class="btn btn-soft">查看更多</a>
                                    </div>
                                </div>
                            </div>