<?php
$z[0]=Array("arcurl","",188,203);
$z[0][4]=array();
$z[1]=Array("litpic","",261,276);
$z[1][4]=array();
$z[2]=Array("title","",296,310);
$z[2][4]=array();
$z[3]=Array("arcurl","",669,684);
$z[3][4]=array();
$z[4]=Array("title","",686,700);
$z[4][4]=array();
$z[5]=Array("pudate","",917,1023);
$z[5][4]=array();
$z[5][4]['function']="Mydate('Y年m月d日 H:M',@me)";
$z[6]=Array("click","",1125,1139);
$z[6][4]=array();
$z[7]=Array("infos","",1313,1327);
$z[7][4]=array();

?>