<?php
$z[0]=Array("arcurl","",120,135);
$z[0][4]=array();
$z[1]=Array("title","",145,159);
$z[1][4]=array();
$z[2]=Array("litpic","",216,231);
$z[2][4]=array();
$z[3]=Array("title","",238,252);
$z[3][4]=array();
$z[4]=Array("typeurl","",440,456);
$z[4][4]=array();
$z[5]=Array("arcurl","",585,600);
$z[5][4]=array();
$z[6]=Array("arcname","",602,618);
$z[6][4]=array();
$z[7]=Array("pubdate","",879,933);
$z[7][4]=array();
$z[7][4]['function "MyDate(Y年m月d日,@me)"']="";

?>