
                                    <li class="nav-item mx-2 [field:global name='autoindex' runphp='yes']@me=@me+1;if(@me==1){@me='active';}else{@me='';}[/field:global]">
                                        <a href="#cid-[field:id/]" class="nav-liank" data-toggle="tab">[field:typename/]</a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </div>
                        <!-- 内容列表 -->
                        <div class="tab-content">
                            <!-- 对应选项卡的内容 -->
                            <div id="#cid-[field:id/]" class="tab-pane">
                                