<?php
$z[0]=Array("field","",47,75);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",115,144);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                                    <li> <a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                    ",274,457);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="6";

?>