<?php
$z[0]=Array("global","(@me==1) ? @me='active': @me='';",58,149);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",195,210);
$z[1][4]=array();
$z[2]=Array("title","",245,259);
$z[2][4]=array();
$z[3]=Array("title","",303,317);
$z[3][4]=array();
$z[4]=Array("arcurl","",549,564);
$z[4][4]=array();
$z[5]=Array("title","",573,587);
$z[5][4]=array();
$z[6]=Array("title","",589,603);
$z[6][4]=array();
$z[7]=Array("infos","",793,807);
$z[7][4]=array();

?>