<li
                                class="carousel-item [field:global name='autoindex' runphp='yes'](@me==1) ? @me='active': @me='';[/field:global]">
                                <img src="[field:litpic/]" width="100%" height="60%" title="[field:title/]"
                                    alt="[field:title/]">
                                <div class="carousel-caption">
                                    <h3 class="text-white">
                                        <strong>
                                            <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                                        </strong>
                                    </h3>
                                    <details>
                                        <p>[field:infos/]</p>
                                    </details>
                                </div>
                            </li>