<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'\r\n									class='preview'><img src='{@me[' litpic']}' /></a>\"); \r\n									",14,192);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",215,230);
$z[1][4]=array();
$z[2]=Array("title","",246,260);
$z[2][4]=array();
$z[3]=Array("pubdate","",333,379);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",414,428);
$z[4][4]=array();
$z[5]=Array("scores","",463,478);
$z[5][4]=array();
$z[6]=Array("description","",533,553);
$z[6][4]=array();

?>