<li >
                            <!-- 图片 -->
                            <a href="[field:arcurl/]" title="[field:title/]">
                            <img src="[field:litpic/]" class="img-thumbnail" width="100%" alt="[field:title/]" title="[field:title/]">
                            </a>
                            <!-- 内容 -->
                            <div id="post-content" class="p-2">
                                <span class="bg-red text-white px-2">
                                    <a href="[field:typelink/]">[field:typename/]</a>
                                </span>
                                <h5 class="text-white">
                                        <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                                </h5>
                                <ul class="d-flex">
                                    <li class="mr-3">
                                        <i class="fa fa-calendar red"></i>
                                        <small class="text-white">[field:pubdate function="Mydate('Y-m-d',@me)"/]</small>
                                    </li>
                                    <li>
                                        <i class="fa fa-comment red"></i>
                                        <small class="text-white">查看：[field:click/]</small>
                                    </li>
                                </ul>
                            </div>
                        </li>