<li class="list-unstyled m-3">
                                <div>
                                    <a href="[field:arcurl/]" title="[field:title/]​" target="_blank">
                                        <img src="[field:litpic/]" alt="[field:title/]" class="thumbnail img-responsive img-rounded">
                                    </a>
                                </div>
                                <h4><a href="[field:arcurl/]" title="[field:title/]​" target="_blank">
                                        <strong>[field:title/]</strong>
                                    </a>
                                </h4>
                                <p> <i class="fas fa-calendar-alt"></i>
                                    [field:pubdate function="MyDate('Y年m月d日',@me)"/]
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                    查看： [field:click/]
                                </p>
                            </li>