<?php
$z[0]=Array("arcurl","",207,222);
$z[0][4]=array();
$z[1]=Array("litpic","",280,295);
$z[1][4]=array();
$z[2]=Array("title","",315,329);
$z[2][4]=array();
$z[3]=Array("arcurl","",688,703);
$z[3][4]=array();
$z[4]=Array("title","",705,719);
$z[4][4]=array();
$z[5]=Array("pudate","",936,1042);
$z[5][4]=array();
$z[5][4]['function']="Mydate('Y年m月d日 H:M',@me)";
$z[6]=Array("click","",1144,1158);
$z[6][4]=array();
$z[7]=Array("infos","",1332,1346);
$z[7][4]=array();

?>