<?php
$z[0]=Array("field","",250,279);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n                                   \r\n                                    <li class=\"nav-item mx-2\">\r\n                                        <a href=\"#catId-[field:typeid/]\" class=\"nav-liank\" data-toggle=\"tab\">[field:typename/]</a>\r\n                                    </li>\r\n                                   ",743,1096);
$z[1][4]=array();
$z[1][4]['type']="son";

?>