<li class="col-lg-4 col-md-6">
                                <!-- 图片 -->
                                <a href="[field:arcurl/]">
                                    <img src="[field:litpic/]" class="img-thumbnail" title="[field:tittle/]" alt="[field:tittle/]">
                                </a>
                                <!-- 内容 -->
                                <div class="post_box mt-2">
                                    <h4 class="title-16">
                                        <a href="[field:arcurl/]" title="[field:tittle/]">[field:tittle/]</a>
                                    </h4>
                                    <span class="small">
                                        <i class="fa fa-calendar"></i>[field:pubdate function="MyDate('Y年m月d日',@me)"/]
                                    </span>
                                    <span class="small"><i class="fa fa-comment"></i>[field:click/]</span>
                                </div>
                            </li>