<div class="col-xl-6 col-lg-6 col-md-6">
                                    <div class="postbox mb-20">
                                        <div class="postbox__thumb">
                                            <a href="[field:arcurl/]">
                                                <img src="[field:litpic/]" alt="[field:title/]">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="postbox__text mb-30">
                                        <h4 class="title-16 font-600 pr-0">
                                            <a href="[field:arcurl/]">[field:title/]</a>
                                        </h4>
                                        <div class="postbox__text-meta pb-10">
                                            <ul>
                                                <li>
                                                    <i class="fas fa-calendar-alt"></i>
                                                    <span>[field:pubdate function="Mydate('Y-m-d',@me)"/]</span>
                                                </li>
                                                <li>
                                                    <i class="far fa-comment"></i>
                                                    <span>查看: [field:click/]</span>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="desc-text mb-20">
                                            <p>[field:info/]</p>
                                        </div>
                                        <a href="[field:arcurl/]" class="btn btn-soft">查看更多</a>
                                    </div>
                                </div>