<li class="d-flex justify-content-between">
                            <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            <span>[field:pubdate function="Mydate('Y-m-d',@me)"/]</span>
                        </li>
                        {/dede arclist}
                    </ul>
                </div>
                <!-- 中部轮播图 -->
                <div class="col-lg-7">
                    <div id="carousel-img" class="carousel p-3 border" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-img" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-img" data-slide-to="1"></li>
                            <li data-target="#carousel-img" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <img src="templets/calipay/img/roll/cat1.jpg" width="100%" height="60%" alt="First slide">
                                <div class="carousel-caption">
                                    <h3>标题</h3>
                                    <p>描述</p>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="templets/calipay/img/roll/cat2.jpg" width="100%" height="60%" alt="Second slide">
                                <div class="carousel-caption">
                                    <h3>标题</h3>
                                    <p>描述</p>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="templets/calipay/img/roll/cat3.jpg" width="100%" height="60%" alt="Third slide">
                                <div class="carousel-caption">
                                    <h3>标题</h3>
                                    <p>描述</p>
                                </div>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carousel-img" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-img" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <!-- 右侧图片头条 -->
                <div class="col-lg-2 d-flex">
                    <div id="roll-right" class="d-flex flex-grow-1 justify-content-around flex-column">
                        <div class=""">
                            <!-- 图片 -->
                            <a href=" #">
                            <img src="templets/calipay/img/roll/1.jpg" class="img-thumbnail" width="100%" alt="">
                            </a>
                            <!-- 内容 -->
                            <div id="post-content" class="p-2">
                                <span class="bg-red text-white px-2">
                                    <a href="#" tabindex="0">花呗</a>
                                </span>
                                <h5 class="text-white">
                                    <a href="#">花呗还款时间有讲究吗？.花呗还款时间有讲究吗？</a>
                                </h5>
                                <ul class="d-flex">
                                    <li class="mr-3">
                                        <i class="fa fa-calendar red"></i>
                                        <small class="text-white">2019-9-17</small>
                                    </li>
                                    <li>
                                        <i class="fa fa-comment red"></i>
                                        <small class="text-white">(03)</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="">
                            <!-- 图片 -->
                            <a href="#">
                                <img src="img/roll/1.jpg" class="img-thumbnail" width="100%" alt="">
                            </a>
                            <!-- 内容 -->
                            <div id="post-content" class="p-2">
                                <span class="bg-red text-white px-2">
                                    <a href="#" tabindex="0">花呗</a>
                                </span>
                                <h5 class="text-white">
                                    <a href="#">花呗还款时间有讲究吗？.花呗还款时间有讲究吗？</a>
                                </h5>
                                <ul class="d-flex">
                                    <li class="mr-3">
                                        <i class="fa fa-calendar red"></i>
                                        <small class="text-white">2019-9-17</small>
                                    </li>
                                    <li>
                                        <i class="fa fa-comment red"></i>
                                        <small class="text-white">(03)</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="">
                            <!-- 图片 -->
                            <a href="#">
                                <img src="img/roll/1.jpg" class="img-thumbnail" width="100%" alt="">
                            </a>
                            <!-- 内容 -->
                            <div id="post-content" class="p-2">
                                <span class="bg-red text-white px-2">
                                    <a href="#" tabindex="0">花呗</a>
                                </span>
                                <h5 class="text-white">
                                    <a href="#">花呗还款时间有讲究吗？.花呗还款时间有讲究吗？</a>
                                </h5>
                                <ul class="d-flex">
                                    <li class="mr-3">
                                        <i class="fa fa-calendar red"></i>
                                        <small class="text-white">2019-9-17</small>
                                    </li>
                                    <li>
                                        <i class="fa fa-comment red"></i>
                                        <small class="text-white">(03)</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- 新闻区 -->
        <section class="container">
            <!-- 标题 -->
            <div class="row">
                <div class="col-12 section-title my-3">
                    <h2>新闻</h2>
                </div>
            </div>
            <!-- 四个新闻 -->
            <ul class="row border">
                <li class="col-lg-3 col-sm-6 px-2">
                    <div class="postbox">
                        <a class="d-block pt-3" href="#">
                            <img class="rounded" src="img/video/fea1.jpg" alt="">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat">
                                    <a href="#" tabindex="0">新闻1</a>
                                </span>
                                <span><i class="fa fa-calendar"></i> 2019年9月19日</span>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="#">意味深长 股转提示非合格投资者投资风险</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>蔡辉</span>
                                <span>评论 (05)</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="col-lg-3 col-sm-6  px-2">
                    <div class="postbox">
                        <a class="d-block pt-3" href="#">
                            <img class="rounded" src="img/video/fea1.jpg" alt="">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat">
                                    <a href="#" tabindex="0">新闻1</a>
                                </span>
                                <span><i class="fa fa-calendar"></i> 2019年9月19日</span>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="#">意味深长 股转提示非合格投资者投资风险</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>蔡辉</span>
                                <span>评论 (05)</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="col-lg-3 col-sm-6 px-2">
                    <div class="postbox">
                        <a class="d-block pt-3" href="#">
                            <img class="rounded" src="img/video/fea1.jpg" alt="">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat">
                                    <a href="#" tabindex="0">新闻1</a>
                                </span>
                                <span><i class="fa fa-calendar"></i> 2019年9月19日</span>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="#">意味深长 股转提示非合格投资者投资风险</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>蔡辉</span>
                                <span>评论 (05)</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="col-lg-3 col-sm-6 px-2">
                    <div class="postbox">
                        <a class="d-block pt-3" href="#">
                            <img class="rounded" src="img/video/fea1.jpg" alt="">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat">
                                    <a href="#" tabindex="0">新闻1</a>
                                </span>
                                <span><i class="fa fa-calendar"></i> 2019年9月19日</span>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="#">意味深长 股转提示非合格投资者投资风险</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>蔡辉</span>
                                <span>评论 (05)</span>
                            </div>
                        </div>
                    </div>
                </li>

            </ul>
        </section>
        <!-- 课堂和广告区域 -->
        <section class="container">
            <!-- 标题 -->
            <div class="row">
                <div class="col-12 section-title my-3">
                    <h2>卡派课堂</h2>
                </div>
            </div>
            <!-- 四个缩略图 -->

            <ul class="row">
                <li class="col-lg-3 col-sm-6">
                    <a href="#">
                        <img class="img-thumbnail" src="img/video/fea1.jpg" alt="">
                    </a>
                </li>
                <li class="col-lg-3 col-sm-6">
                    <a href="#">
                        <img class="img-thumbnail" src="img/video/fea2.jpg" alt="">
                    </a>
                </li>
                <li class="col-lg-3  col-sm-6">
                    <a href="#">
                        <img class="img-thumbnail" src="img/video/fea3.jpg" alt="">
                    </a>
                </li>
                <li class="col-lg-3 col-sm-6">
                    <a href="#">
                        <img class="img-thumbnail" src="img/video/fea4.jpg" alt="">
                    </a>
                </li>
            </ul>

        </section>

        <!-- 循环分类楼层 -->
        <section class="container">
            <div class="row">
                <!-- 左侧部分 -->
                <div class="col-lg-8">
                    <!-- 大循环楼层 -->
                    <div class="content-pad border px-3">
                        <!-- 标题 -->
                        <div class="row bg-grey m-3">
                            <div class="col-md-4 col-sm-12 title-theme pl-0">
                                <h2>花呗</h2>
                            </div>
                            <div class="col-md-8 col-sm-12 m-auto">
                                <ul class="nav nav-tabs news-tabs justify-content-end">
                                    <li class="nav-item mx-2">
                                        <a href="#catId-1" class="nav-liank active" data-toggle="tab">花呗申请</a>
                                    </li>
                                    <li class="nav-item mx-2">
                                        <a href="#catId-2" class="nav-liank" data-toggle="tab">花呗注册</a>
                                    </li>
                                    <li class="nav-item mx-2">
                                        <a href="#catId-3" class="nav-liank" data-toggle="tab">花呗技巧</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- 内容列表 -->
                        <div class="tab-content">
                            <!-- 对应选项卡的内容 -->
                            <div id="catId-1" class="tab-pane active">
                                <ul class="row">
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- 对应选项卡的内容 -->
                            <div id="catId-2" class="tab-pane">
                                <ul class="row">
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea2.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea2.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- 对应选项卡的内容 -->
                            <div id="catId-3" class="tab-pane">
                                <ul class="row">
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea3.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea3.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                    <li class="col-lg-4 col-md-6">
                                        <!-- 图片 -->
                                        <a href="#">
                                            <img src="img/video/fea1.jpg" class="img-thumbnail" alt="">
                                        </a>
                                        <!-- 内容标题 -->
                                        <div class="post_box mt-2">
                                            <h4 class="title-16">
                                                <a href="#" alt="" title="">月入5000网贷80万：普通人，这4样东西千万不能碰</a>
                                            </h4>
                                            <span><i class="fa fa-calendar"></i> <small>2019年9月19日</small></span>
                                            <span><i class="fa fa-comment"></i><small>03</small></span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>


                <!-- 右侧部分 -->
                {dede:include filename="right.htm"