<?php
$z[0]=Array("array","\r\n								@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'class='preview'><img\r\n										src='{@me[' litpic']}' /></a>\");\r\n								",26,212);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",235,250);
$z[1][4]=array();
$z[2]=Array("title","",266,280);
$z[2][4]=array();
$z[3]=Array("pubdate","",386,443);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",512,526);
$z[4][4]=array();
$z[5]=Array("description","",589,609);
$z[5][4]=array();

?>