<?php
$z[0]=Array("field","",4,33);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n           \n                    <h4 class=\"title-18 pr-0\">\n                        <a href=\"[field:arcurl/]\">[field:title/]</a>\n                    </h4>\n                    <div class=\"postbox__text-meta pb-10\">\n                        <ul>\n                            <li>\n                                <i class=\"fas fa-calendar-alt\"></i>\n                                <span>[field:pubdate function=\"('Y年m月d日',@me)\"/]</span>\n                            </li>\n                           \n                        </ul>\n                    </div>\n                </div>\n            </div>\n            ",70,743);
$z[1][4]=array();
$z[1][4]['row']="1";
$z[1][4]['flag']="h";
$z[1][4]['orderby']="rand";

?>