<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'\r\n									class='preview'><img src='{@me[' litpic']}' /></a>\"); ",14,181);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",200,215);
$z[1][4]=array();
$z[2]=Array("title","",231,245);
$z[2][4]=array();
$z[3]=Array("pubdate","",313,359);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",394,408);
$z[4][4]=array();
$z[5]=Array("scores","",443,458);
$z[5][4]=array();
$z[6]=Array("description","",513,533);
$z[6][4]=array();

?>