<div class="col-xl-3 col-lg-4 col-md-6">
                            <div class="postbox mb-25">
                                <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                    <a href="[field:arcurl/]">
                                        <img src="[field:litpic/]" alt="[field:title/]">
                                    </a>
                                </div>
                                <div class="postbox__text pt-20">
                                    <div class="meta-top">
                                        <span class="post-cat mb-10 mr-10">
                                            <a href="[field:arcurl/]" tabindex="0">[field:typename/]</a>
                                        </span>
                                        <span><i class="fas fa-calendar-alt"></i> [field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                    </div>
                                    <h4 class="title-16 pr-0">
                                        <a href="[field:arcurl/]">[field:title/]</a>
                                    </h4>
                                    <div class="postbox__text-meta pb-10">
                                        <ul>
                                            <li>
                                                <span>[field:writer/]</span>
                                            </li>
                                            <li>
                                                <span>Comments (05)</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>