<?php
$z[0]=Array("field","",250,279);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n                                    <li class=\"nav-item mx-2 [field:global name='autoindex' runphp='yes']@me=@me+1;if(@me==1){@me='active';}else{@me='';}[/field:global]\">\r\n                                        <a href=\"#cid-[field:id/]\" class=\"nav-liank\" data-toggle=\"tab\">[field:typename/]</a>\r\n                                    </li>\r\n                                    ",571,990);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[2]=Array("field","",1314,1330);
$z[2][4]=array();
$z[2][4]['name']="id";

?>