<div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="[field:arcurl/]">
                                                            <img src="[field:litpic/]" alt="[field:title/]">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">[field:title/]</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>