<?php
$z[0]=Array("arcurl","",150,165);
$z[0][4]=array();
$z[1]=Array("litpic","",219,234);
$z[1][4]=array();
$z[2]=Array("title","",243,257);
$z[2][4]=array();
$z[3]=Array("title","",264,278);
$z[3][4]=array();
$z[4]=Array("arcurl","",720,735);
$z[4][4]=array();
$z[5]=Array("title","",737,751);
$z[5][4]=array();
$z[6]=Array("pubdate","",1108,1162);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日',@me)";

?>