<?php
$z[0]=Array("field","",148,176);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",194,263);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\n                                    <div class=\"post__small-text fix pl-10\">\n                                       \n                                        <div class=\"post__small-text-meta\">\n                                            <ul>\n                                                <li>\n                                                    <i class=\"fas fa-calendar-alt\"></i>\n                                                    <span>[field:pubdate function=\"('Y-m-d',@me)\"/]</span>\n                                                </li>\n                                            </ul>\n                                        </div>\n                                    </div>\n                                    ",459,1217);
$z[2][4]=array();
$z[2][4]['row']="2";

?>