<div class="post__small-text fix pl-10">
                                       
                                        <div class="post__small-text-meta">
                                            <ul>
                                                <li>
                                                    <i class="fas fa-calendar-alt"></i>
                                                    <span>[field:pubdate function="('Y-m-d',@me)"/]</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>