<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'\r\n								class='preview'><img src='{@me[' litpic']}' /></a>\"); ",13,179);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",197,212);
$z[1][4]=array();
$z[2]=Array("title","",228,242);
$z[2][4]=array();
$z[3]=Array("pubdate","",308,354);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",388,402);
$z[4][4]=array();
$z[5]=Array("scores","",436,451);
$z[5][4]=array();
$z[6]=Array("description","",503,523);
$z[6][4]=array();

?>