<?php
$z[0]=Array("global","(@me==1) ? @me='active': @me='';",25,116);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",162,177);
$z[1][4]=array();
$z[2]=Array("title","",212,226);
$z[2][4]=array();
$z[3]=Array("title","",270,284);
$z[3][4]=array();
$z[4]=Array("arcurl","",443,458);
$z[4][4]=array();
$z[5]=Array("title","",467,481);
$z[5][4]=array();
$z[6]=Array("title","",483,497);
$z[6][4]=array();
$z[7]=Array("infos","",585,599);
$z[7][4]=array();

?>