<li class="carousel-item [field:global name='autoindex' runphp='yes'](@me==1) ? @me='active': @me='';[/field:global]">
                                <img src="[field:litpic/]" width="100%" height="60%" title="[field:title/]"
                                    alt="[field:title/]">
                                <div class="carousel-caption">
                                    <h3>
                                        <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                                    </h3>
                                    <p>[field:infos/]</p>
                                </div>
                            </li>