<li class="col-lg-4 col-md-6">
                                <!-- 图片 -->
                                <a href="[field:arcurl/]">
                                    <img src="[field:litpic/]" class="img-thumbnail" alt="[field:title/]">
                                </a>
                                <!-- 内容标题 -->
                                <div class="post_box mt-2">
                                    <h4 class="title-16">
                                        <a href="[field:arcurl/]" alt="[field:title/]"
                                            title="[field:title/]">[field:title/]</a>
                                    </h4>
                                    <time>
                                        <i class="fa fa-calendar red"></i>[field:pubdate function="Mydate('Y-m-d',@me)"/]
                                    </time>
                                    <span><i class="fa fa-eye red"></i><small>阅读：[field:click/]</small></span>
                                </div>
                            </li>