<li class="widget-article d-flex p-2">
                <div class="w-50">
                    <a href="[field:arcurl/]" class="d-block">
                        <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]">
                    </a>
                </div>
                <div class="ml-2">
                    <span class="sm-cat">
                        <a href="[field:typeurl/]">[field:typename/]</a>
                    </span>
                    <h4 class="title-16 pr-0">
                        <a href="[field:arcurl/]">[field:title/]</a>
                    </h4>
                    <ul>
                        <li class="mr-3">
                            <i class="fa fa-calendar red"></i>
                            <small>[field:pubdate function="MyDate('Y-m-d',@me)"/]</small>
                        </li>
                    </ul>
                </div>
            </li>