<?php
$z[0]=Array("array","\r\n								@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'class='preview'><img\r\n										src='{@me[' litpic']}' /></a>\");\r\n								",40,226);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",249,264);
$z[1][4]=array();
$z[2]=Array("title","",280,294);
$z[2][4]=array();
$z[3]=Array("pubdate","",400,457);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",526,540);
$z[4][4]=array();
$z[5]=Array("description","",603,623);
$z[5][4]=array();

?>