<div class="col-lg-4 col-md-4">
                                        <div class="postbox mb-30">
                                            <div class="postbox__thumb">
                                                <a href="[filed:arcurl/]">
                                                    <img class="img-100" title="[filed:tittle/]"
                                                        src="[filed:litpic/]"
                                                        alt="[filed:tittle/]">
                                                </a>
                                            </div>
                                            <div class="postbox__text pt-10">
                                                <div class="postbox__text-meta pb-10">
                                                    <ul>
                                                        <li>
                                                            <i class="fas fa-calendar-alt"></i>
                                                            <span>[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span>
                                                        </li>
                                                        <li>
                                                            <i class="far fa-comment"></i>
                                                            <span>查看： [field:click/]</span>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <h4 class="pr-0">
                                                    <a href="[filed:arcurl/]">[filed:tittle/]</a>
                                                </h4>
                                            </div>
                                        </div>
                                    </div>