<?php
$z[0]=Array("typeurl","",17,33);
$z[0][4]=array();
$z[1]=Array("typename","",48,65);
$z[1][4]=array();
$z[2]=Array("pubdate","",164,211);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Y-m-d',@me)";
$z[3]=Array("arcurl","",283,298);
$z[3][4]=array();
$z[4]=Array("title","",300,314);
$z[4][4]=array();
$z[5]=Array("click","",379,393);
$z[5][4]=array();
$z[6]=Array("info","",465,478);
$z[6][4]=array();

?>