<?php
$z[0]=Array("field","",8,30);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",31,53);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","               \r\n                <ul class='autod'>                    \r\n                    <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>                \r\n                </ul>           \r\n                ",75,342);
$z[2][4]=array();
$z[2][4]['titlelen']="42";
$z[2][4]['row']="3";

?>