<div class="hero__thumb" data-overlay="dark-gradient">
                                    <a href="[field:arcurl/]"><img src="[field:litpic/]" alt="hero image"></a>
                                </div>
                                <div class="hero__text">
                                    <span class="post-cat mb-10"><a href="#">头条</a></span>
                                    <h3 class="pr-100"><a href="[field:arcurl/]">[field:title/]</a></h3>
                                </div>