<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'\r\n							class='preview'><img src='{@me[' litpic']}' /></a>\"); ",12,177);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",194,209);
$z[1][4]=array();
$z[2]=Array("title","",225,239);
$z[2][4]=array();
$z[3]=Array("pubdate","",303,349);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",382,396);
$z[4][4]=array();
$z[5]=Array("scores","",429,444);
$z[5][4]=array();
$z[6]=Array("description","",493,513);
$z[6][4]=array();

?>