<?php
$z[0]=Array("arcurl","",212,227);
$z[0][4]=array();
$z[1]=Array("litpic","",285,300);
$z[1][4]=array();
$z[2]=Array("title","",320,334);
$z[2][4]=array();
$z[3]=Array("arcurl","",689,704);
$z[3][4]=array();
$z[4]=Array("title","",706,720);
$z[4][4]=array();
$z[5]=Array("pudate","",941,1047);
$z[5][4]=array();
$z[5][4]['function']="Mydate('Y年m月d日 H:i',@me)";
$z[6]=Array("click","",1153,1167);
$z[6][4]=array();
$z[7]=Array("infos","",1341,1355);
$z[7][4]=array();

?>