<li class="row mb-3 py-3 border-bottom">
                                <div class="col-md-4">
                                    <div class="postbox_thumb">
                                        <a href="[field:arcurl/]">
                                            <img src="[field:litpic/]" width="100%" alt="[field:title/]">
                                        </a>
                                    </div>

                                </div>
                                <div class="col-md-8">
                                    <div class="postbox_text">
                                        <h3>
                                            <a href="[field:arcurl/]">[field:title/]</a>
                                        </h3>
                                        <div class="postbox_text-meta pb-2">
                                            <span> <i class="fa fa-calendar red mr-2"></i>[field:pudate
                                                function="Mydate('Y年m月d日 H:i',@me)"/]</span>
                                            <span><i class="fa fa-comment red mr-2"></i>查看：[field:click/]</span>
                                        </div>
                                        <div class="desc-text mb-2">
                                            <p>[field:infos/]</p>
                                        </div>
                                    </div>
                                </div>
                            </li>