<div class="post__small-thumb f-left">
                    <a href="[field:arcurl/]"  title="[field:title/]​" target="_blank">
                        <img src="[field:litpic/]" alt="[field:title/]">
                    </a>
                </div>
                <div class="post__small-text fix pl-10">
                    <span class="sm-cat">
                        <a href="[field:typeurl/]">[typename/]</a>
                    </span>
                    <h4 class="title-13 pr-0">
                        <a href="[field:arcurl/]">[field:arcname/]</a>
                    </h4>
                    <div class="post__small-text-meta">
                        <ul>
                            <li>
                                <i class="fas fa-calendar-alt"></i>
                                <span>[field:pubdate function "MyDate('Y年m月d日',@me)"/]</span>
                            </li>
                        </ul>
                    </div>
                </div>