<?php
$z[0]=Array("arcurl","",69,84);
$z[0][4]=array();
$z[1]=Array("title","",94,108);
$z[1][4]=array();
$z[2]=Array("litpic","",165,180);
$z[2][4]=array();
$z[3]=Array("title","",187,201);
$z[3][4]=array();
$z[4]=Array("typeurl","",389,405);
$z[4][4]=array();
$z[5]=Array("arcurl","",534,549);
$z[5][4]=array();
$z[6]=Array("arcname","",551,567);
$z[6][4]=array();
$z[7]=Array("pubdate","",828,882);
$z[7][4]=array();
$z[7][4]['function "MyDate(Y年m月d日,@me)"']="";

?>