<?php
$z[0]=Array("arcurl","",137,152);
$z[0][4]=array();
$z[1]=Array("title","",162,176);
$z[1][4]=array();
$z[2]=Array("litpic","",233,248);
$z[2][4]=array();
$z[3]=Array("title","",255,269);
$z[3][4]=array();
$z[4]=Array("typeurl","",457,473);
$z[4][4]=array();
$z[5]=Array("arcurl","",602,617);
$z[5][4]=array();
$z[6]=Array("arcname","",619,635);
$z[6][4]=array();
$z[7]=Array("pubdate","",896,950);
$z[7][4]=array();
$z[7][4]['function "MyDate(Y年m月d日,@me)"']="";

?>