<?php
$z[0]=Array("arcurl","",105,120);
$z[0][4]=array();
$z[1]=Array("litpic","",174,189);
$z[1][4]=array();
$z[2]=Array("title","",198,212);
$z[2][4]=array();
$z[3]=Array("title","",219,233);
$z[3][4]=array();
$z[4]=Array("arcurl","",487,502);
$z[4][4]=array();
$z[5]=Array("title","",504,518);
$z[5][4]=array();
$z[6]=Array("pubdate","",682,729);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>