-->
                        <div class="post__small mb-30">
                            <div class="post__small-thumb f-left">
                                <a href="[field:arcurl/]">
                                    <img src="[field:litpic/]" alt="hero image">
                                </a>
                            </div>
                            <div class="post__small-text fix pl-10">
                                <h4 class="title-16 pr-0 mt-0">
                                    <a href="[field:arcurl/]">[field:title/]</a>
                                </h4>
                                <div class="post__small-text-meta">
                                    <ul>
                                        <li>
                                            <i class="fas fa-calendar-alt"></i>
                                            <span>[field:pubdate function="('Y-m-d',@me)"/]</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--