<?php
$z[0]=Array("array","\r\n								@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'class='preview'><img src='{@me[' litpic']}' /></a>\");\r\n								",14,189);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",212,227);
$z[1][4]=array();
$z[2]=Array("title","",243,257);
$z[2][4]=array();
$z[3]=Array("pubdate","",334,380);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",415,429);
$z[4][4]=array();
$z[5]=Array("scores","",464,479);
$z[5][4]=array();
$z[6]=Array("description","",534,554);
$z[6][4]=array();

?>