<li class="col-lg-3 col-sm-6 px-2">
                    <div class="postbox m-2">
                        <a class="d-block pt-3" href="[field:arcurl/]">
                            <img src="[field:litpic/]" width="100%" class="rounded" alt="[field:title/]"
                                title="[field:title/]">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat mr-4">
                                    <a href="[field:typelink/]" tabindex="0">[field:typename/]</a>
                                </span>
                                <i class="fa fa-calendar mr-2"></i>
                                <time class="small">[field:pubdate function="Mydate('Y年m月d日',@me)"/]</time>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>
                                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>[field:writer/]
                                </span>
                                <span>
                                    <i class="fa fa-eye mr-2"></i>查看：[field:click/]
                                </span>
                            </div>
                        </div>
                    </div>
                </li>