<?php
$z[0]=Array("arcurl","",148,163);
$z[0][4]=array();
$z[1]=Array("litpic","",216,231);
$z[1][4]=array();
$z[2]=Array("title","",240,254);
$z[2][4]=array();
$z[3]=Array("title","",261,275);
$z[3][4]=array();
$z[4]=Array("arcurl","",709,724);
$z[4][4]=array();
$z[5]=Array("title","",726,740);
$z[5][4]=array();
$z[6]=Array("pubdate","",1091,1145);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日',@me)";

?>