<?php
$z[0]=Array("array","\r\n								@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'class='preview'><img\r\n										src='{@me[' litpic']}' /></a>\");\r\n								",14,200);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",223,238);
$z[1][4]=array();
$z[2]=Array("title","",254,268);
$z[2][4]=array();
$z[3]=Array("pubdate","",374,431);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",500,514);
$z[4][4]=array();
$z[5]=Array("scores","",591,606);
$z[5][4]=array();
$z[6]=Array("description","",669,689);
$z[6][4]=array();

?>