<li class="col-lg-3 col-sm-6 px-2">
                    <div class="postbox">
                        <a class="d-block pt-3" href="[field:arcurl/]">
                            <img src="[field:litpic/]" class="rounded" alt="[field:title/]"
                                title="[field:title/]">
                        </a>
                        <div class="post_text py-3">
                            <div class="meta-top">
                                <span class="post-cat">
                                    <a href="[field:typelink/]" tabindex="0">[field:typename/]</a>
                                </span>
                                <span><i class="fa fa-calendar"></i>[field:pubdate
                                    function="Mydate('Y年m月d日',@me)"/]</span>
                            </div>
                            <h4 class="title-16 pr-0">
                                <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                            </h4>
                            <div class="postbox_text-meta">
                                <span>[field:write/]</span>
                                <span>查看：[field:click/]</span>
                            </div>
                        </div>
                    </div>
                </li>