<?php
$z[0]=Array("field","",132,160);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",178,207);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\n                            <div class=\"post__small mb-30\">\n                      \n                        \n                        \n                        </div>\n                        ",313,539);
$z[2][4]=array();
$z[2][4]['row']="2";

?>