<div class="col-xl-4 col-lg-4 col-md-6">
                    <div class="section-title mb-30">
                        <h2><a href="{dede:field name='typeurl'/}" target="_blank">{dede:field name='typename'/}</a>
                    </div>
                    <div class="cat-sm-post">
                            {dede:arclist row='2'}
                            <div class="post__small mb-30">
                      
                        
                        
                        </div>
                        {/dede:arclist}
                    </div>


                
                </div>