<div class="carousel-item">
                            <img src="[field:litpic/]" width="100%" height="60%" title="[field:title/]"
                                alt="[field:title/]">
                            <div class="carousel-caption">
                                <h3>[field:title/]</h3>
                                <p>[field:infos/]</p>
                            </div>
                        </div>