<li>
                            <div>
                                <a href="[field:arcurl/]" title="[field:title/]" target="_blank">
                                    <img src="[field:litpic/]" alt="[field:title/]" /></a>
                            </div>
                            <h4><a href="[field:arcurl/]" target="_blank"> [field:title/]</a></h4>
                            <span class="date"> [field:pubdate function="MyDate('Y年m月d日',@me)"/]</span>
                        </li>