<?php
$z[0]=Array("arcurl","",80,95);
$z[0][4]=array();
$z[1]=Array("title","",104,118);
$z[1][4]=array();
$z[2]=Array("litpic","",183,198);
$z[2][4]=array();
$z[3]=Array("title","",205,219);
$z[3][4]=array();
$z[4]=Array("arcurl","",304,319);
$z[4][4]=array();
$z[5]=Array("title","",338,352);
$z[5][4]=array();
$z[6]=Array("pubdate","",410,464);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日',@me)";

?>