<li class="list-unstyled m-3">
                        <div>
                            <a href="[field:arcurl/]" title="[field:title/]​" target="_blank">
                                <img src="[field:litpic/]"alt="[field:title/]">                              
                            </a>
                        </div>
                        <h3><a href="[field:arcurl/]" title="[field:title/]​" target="_blank">
                            <strong>[field:title/]</strong>
                        </a>
                        </h3>
                        <p> [field:pubdate function="MyDate('Y年m月d日',@me)"/]
                                查看： [field:click/]
                            </p>
                    </li>