<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['\r\n										arcurl']}' class='preview'><img src='{@me[' litpic']}' /></a>\"); ",15,183);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",203,218);
$z[1][4]=array();
$z[2]=Array("title","",234,248);
$z[2][4]=array();
$z[3]=Array("pubdate","",318,364);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",400,414);
$z[4][4]=array();
$z[5]=Array("scores","",450,465);
$z[5][4]=array();
$z[6]=Array("description","",523,543);
$z[6][4]=array();

?>