<div class="news-tab-area">
                                <div class="news-tab-part grey-bg clearfix mb-30">
                                    <div class="title-theme f-left">
                                        <h2>{dede:field.typename/}</h2>
                                    </div>
                                    <ul class="nav news-tabs f-right" id="myTab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                                role="tab" aria-controls="home" aria-selected="true">science </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile"
                                                role="tab" aria-controls="profile" aria-selected="false">travel</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact"
                                                role="tab" aria-controls="contact" aria-selected="false">fashion</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="home" role="tabpanel"
                                        aria-labelledby="home-tab">
                                        <div class="row">
                                            {dede:arclist row=6}
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="[field:arcurl/]">
                                                            <img src="[field:litpic/]" alt="[field:title/]">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">[field:title/]</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            {/dede:arclist}                                          
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="profile" role="tabpanel"
                                        aria-labelledby="profile-tab">
                                        <div class="row">
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab6.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Patriots release WR Jordan Matthews after
                                                                significant</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab2.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Urban Meyer faces questions about domestic
                                                                viole...</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab1.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">DNA-testing companies pro mise not to share
                                                                informa</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab3.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Giant hands lift new Vietnan bridge toward
                                                                heavens</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab5.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Congrats! Because you live Dhaka can book
                                                                these</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab4.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">'Mars' actor says working on the NatGeo
                                                                series</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="contact" role="tabpanel"
                                        aria-labelledby="contact-tab">
                                        <div class="row">
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab2.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Urban Meyer faces questions about domestic
                                                                viole...</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab5.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Congrats! Because you live Dhaka can book
                                                                these</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab1.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">DNA-testing companies pro mise not to share
                                                                informa</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab6.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Patriots release WR Jordan Matthews after
                                                                significant</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab3.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">Giant hands lift new Vietnan bridge toward
                                                                heavens</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-4 col-lg-6 col-md-6">
                                                <div class="postbox mb-25">
                                                    <div class="postbox__thumb" data-overlay="dark" data-opacity="2">
                                                        <a href="#">
                                                            <img src="/templets/calipay/img/news2/tab4.jpg" alt="hero image">
                                                        </a>
                                                    </div>
                                                    <div class="postbox__text pt-15">
                                                        <div class="postbox__text-meta pb-10">
                                                            <ul>
                                                                <li>
                                                                    <i class="fas fa-calendar-alt"></i>
                                                                    <span>01 Sep 2018</span>
                                                                </li>
                                                                <li>
                                                                    <i class="far fa-comment"></i>
                                                                    <span>(03)</span>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <h4 class="title-14 font-600 pr-0">
                                                            <a href="#">'Mars' actor says working on the NatGeo
                                                                series</a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>