<li class="my-2">
                            <!-- 图片 -->
                            <a href="[field:arcurl/]" title="[field:title/]">
                                <img src="[field:litpic/]" class="img-thumbnail" width="100%" height="60%"
                                    alt="[field:title/]" title="[field:title/]">
                            </a>
                            <!-- 内容 -->
                            <div id="post-content" class="p-2">
                                <span class="badge badge-danger px-2">
                                    [field:typelink/]
                                </span>
                                <h5 class="text-white">
                                    <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
                                </h5>
                            </div>
                        </li>