<div class="postbox mb-25">                             
                            <div class="postbox__thumb">
                                <a href="[field:arcurl/]">
                                    <img src="[field:litpic/]" alt="hero image">
                                </a>
                            </div>
                            <div class="postbox__text pt-10">
                                <div class="postbox__text-meta pb-10">
                                    <ul>
                                        <li>
                                            <i class="fas fa-calendar-alt"></i>
                                            <span>[field:pubdate function="MyDate('Y年m月d日' ,@me)"/]</span>
                                        </li>
                                        <li>
                                            <i class="far fa-comment"></i>
                                            <span>(03)</span>
                                        </li>
                                    </ul>
                                </div>
                                <h4 class="pr-0">
                                    <a href="[field:arcurl/]">[field:title/]</a>
                                </h4>
                            </div>
                        </div>