<?php
$z[0]=Array("global","",575,602);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1245,1272);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1350,1376);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1408,1434);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1557,1584);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1851,1878);
$z[5][4]=array();
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("channelartlist","\r\n                    <li class=\"nav-li\">\r\n                        <a href=\"{dede:field name='typeurl'/}\" class=\"dropdown-toggle\">{dede:field name='typename'/}</a>\r\n                        <ul class=\"submenu\">\r\n                            {dede:channel type='son' row='6'}\r\n                            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                            {/dede:channel}\r\n                        </ul>\r\n                    </li>\r\n                    ",2220,2778);
$z[6][4]=array();
$z[6][4]['row']="8";
$z[6][4]['typeid']="1,2,3,4,16,5";
$z[7]=Array("type","\r\n                    <li>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n                    ",2800,2984);
$z[7][4]=array();
$z[7][4]['typeid']="6";
$z[8]=Array("type","\r\n                    <li>\r\n                        <a href=\"[field:typelink/]\" .rel=\"nofollow\">[field:typename/]</a>\r\n                    </li>\r\n                    ",3006,3206);
$z[8][4]=array();
$z[8][4]['typeid']="7";

?>