<?php
$z[0]=Array("channel","\r\n            <li>\r\n                <i class=\"fa fa-hand-o-right mr-2\"></i>\r\n                <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            </li>\r\n            ",364,587);
$z[0][4]=array();
$z[0][4]['row']="12";
$z[0][4]['type']="son";
$z[1]=Array("arclist","\r\n            <li class=\"widget-article d-flex p-2\">\r\n                <div class=\"w-50\">\r\n                    <a href=\"[field:arcurl/]\" class=\"d-block\">\r\n                        <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\">\r\n                    </a>\r\n                </div>\r\n                <div class=\"ml-2\">\r\n                    <span class=\"badge badge-danger\">热门</span>\r\n                    <h4>\r\n                        <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                    </h4>\r\n                    <time class=\"small\">\r\n                        <i class=\"fa fa-calendar red mr-2\"></i>\r\n                        [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]\r\n                    </time>\r\n                </div>\r\n            </li>\r\n            ",813,1658);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['orderby']="click";
$z[2]=Array("arclist","\r\n            <li class=\"widget-article d-flex p-2\">\r\n                <div class=\"w-50\">\r\n                    <a href=\"[field:arcurl/]\" class=\"d-block\">\r\n                        <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\">\r\n                    </a>\r\n                </div>\r\n                <div class=\"ml-2\">\r\n                    <span class=\"badge badge-primary\">推荐</span>\r\n                    <h4>\r\n                        <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                    </h4>\r\n                    <time class=\"small\">\r\n                        <i class=\"fa fa-calendar red mr-2\"></i>\r\n                        [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]\r\n                    </time>\r\n                </div>\r\n            </li>\r\n            ",1884,2732);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("tag","\r\n            <a href=\"[field:link/]\">[field:tag/]</a>\r\n            ",2976,3085);
$z[3][4]=array();
$z[3][4]['row']="20";
$z[3][4]['getall']="1";

?>